### ISSUE TITLE
Coule you share the ckpt of the homegrid ?

### ISSUE THREAD

**Issue by Lr-2002** [jlin816/dynalang#11]

**Comment by jlin816** [comment]
Hi, I don't have time to put together the checkpoints at the moment, but I'll prioritize this if many others request it as well :)

**Comment by Lr-2002** [comment]
Sure, if you have time, please share it with us. We are all following your work~

**Comment by glue25** [comment]
Thanks to the author for this wonderful work, I also hope that the author can provide a checkpoint.

**Comment by chjchjchjchjchj** [comment]
Could you please consider releasing the model checkpoint as well? It would be greatly appreciated.

**Comment by ruiiu** [comment]
Hi could you please release the trained model checkpoints. Thanks very much.

**Comment by jlin816** [comment]
Hi! Unfortunately I don't have the checkpoints anymore, but I'm happy to help with debugging any training.
