### ISSUE TITLE
How long does it take to train the homegrid environment on a single 3090 GPU?

### ISSUE THREAD

**Issue by liruiluo** [jlin816/dynalang#12]
This is really a great work!
I encountered a problem when running the homegrid environment: only 100k steps were run in 3 days, which is much slower than the number reported in the paper (3.75 GPU days 50M steps). Is there something I overlooked?

**Comment by jlin816** [comment]
Hi, are you using the `parallel` train script? You can see an example of usage here: `https://github.com/jlin816/dynalang/blob/main/scripts/run_vln.sh` , which you can modify for homegrid by setting a larger number of envs depending on your machine. We used:
```
--envs.amount 66 \ 
--run.actor_batch 32 \
--run.actor_threads 4
```
Hope that helps!
