### ISSUE TITLE
What default rssm_type should be?

### ISSUE THREAD

**Issue by eadadi** [jlin816/dynalang#13]
Hi, I see that in the configs `rssm_type=rssm`. The RSSM does not receive text as one of it modalities right?
Are the configs defaults to the original DreamerV3?

I would love to get clarification about that

**Comment by jlin816** [comment]
Hi, text observations are specified as inputs/outputs to the model through encoder/decoder config `mlp_keys` (`.*` by default, which matches all keys with a certain shape).

You can also override it like this: https://github.com/jlin816/dynalang/blob/main/dynalang/configs.yaml#L282-L299
