### ISSUE TITLE
Trouble setting up environment for Messenger 

### ISSUE THREAD

**Issue by realjoenguyen** [jlin816/dynalang#2]
Hi, 

Thanks for the nice work, 

May I ask if you can provide a docker or a Conda env yml file so I can create the environment for Messenger? I am using slurm server in which I can't use `sudo apt-get` to set up dependencies. 

I can use `pygame` dependencies for Conda but unfortunately, they are for `python<=3.7`, while the jax codebase is for `python>=3.8`.

Thank you for your help, 

Joe

**Comment by jlin816** [comment]
I've been using Python 3.8, but the codebase should still work with Python 3.7 — have you tried running it? If that doesn't work I can try to provide a Dockerfile to start with.

**Comment by realjoenguyen** [comment]
Yes, I tried that but it didn't work. 

Jax 0.4.* isn't compatible with python 3.7.

**Comment by jlin816** [comment]
I just added a Dockerfile that I tested with Messenger. Hope that helps! Feel free to open another issue if you run into other problems.
