### ISSUE TITLE
FileNotFoundError: dynalang/embodied/envs/data/vln_embeds_t5.pkl

### ISSUE THREAD

**Issue by ttccxx** [jlin816/dynalang#3]
Hi! Thanks for the great work!

I'm trying to run the VLN env following the instruction, but encounted the error: 
"FileNotFoundError: dynalang/embodied/envs/data/vln_embeds_t5.pkl"

I'm not sure if I missed it somewhere, can you provide a link to this file? Thanks!

**Comment by jlin816** [comment]
Thanks! I updated the README with instructions to download the file:

Download the pre-embedded sentences from [Google Drive](https://drive.google.com/drive/u/0/folders/1XuacEUmWAvPtYBJ5YEc21yV7aExzPY1X) and place the pkl file into `dynalang/embodied/envs/data`.
