### ISSUE TITLE
Errors when installing dependencies

### ISSUE THREAD

**Issue by haoqiusong** [jlin816/dynalang#4]
Hi,

I've been struggling with the installation issue for a while. When I tried pip install -e ., I always got

ERROR: Command errored out with exit status 1:
     command: /dynalang-main/myenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/dynalang-main/setup.py'"'"'; __file__='"'"'/dynalang-main/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/haoqiu/course/dynalang-main/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /dynalang-main/myenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/dynalang-main/setup.py'"'"'; __file__='"'"'/dynalang-main/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

Is there any way to get rid of this? Much appreciated!

**Comment by jlin816** [comment]
Could you try deleting `setup.py` and re-running the pip install?

If that doesn't work, you can always install the dependencies listed in `pyproject.toml` manually.
