### ISSUE TITLE
request for help 

### ISSUE THREAD

**Issue by Pear-Jun** [jlin816/dynalang#6]
Hi
When I try to run "sh scripts/run_homegrid.sh homegrid_task EXP_NAME GPU_IDS 12" ,the following error occured.

RuntimeError: Unknown backend: 'gpu' requested, but no platforms that are 
instances of gpu are present. Platforms present are: cpu

the conda env i follow you pyproject.toml

**Comment by jlin816** [comment]
Did you pass a GPU ID where `GPU_IDS` is in the command? If you don't have a GPU you'll have to run with the additional flag `--jax.platform cpu`.
