### ISSUE TITLE
How to run parallel script in multi-GPUs

### ISSUE THREAD

**Issue by qiwang067** [jlin816/dynalang#7]
Hi, Lin, we want to use the parallel script for training speedups, but don't know how to run it in multi-GPUs. Also, we wonder that the effect of speed up exmaple(`scripts/run_vln.sh`)  . Does the speed-up example executed in only one GPU?

**Comment by jlin816** [comment]
You can do both multi-GPU and parallel script just by adding the flags `--jax.train_devices <comma-separated gpu ids for training>` and `--jax.policy_devices <gpu ids for policy>`. For the VLN environment we trained on 8 GPUs with the parallel script.
