### ISSUE TITLE
 Issue Installing JAX with CUDA 11 and cuDNN 82 Support for VLN Experiment

### ISSUE THREAD

**Issue by LittleGuoKe** [jlin816/dynalang#9]
Hello Jessy Lin,

I am currently working on a project involving Virtual Language Navigation (VLN) and have encountered an issue with the installation of JAX. I tried installing JAX with specific CUDA and cuDNN support using the following command:

`pip install "jax[cuda11_cudnn82]==0.4.8" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

However, I received the following error message:

`ERROR: No matching distribution found for jaxlib==0.4.7+cuda11.cudnn82; extra == "cuda11_cudnn82"`

It seems that the specified version of JAX (0.4.8) with CUDA 11 and cuDNN 82 support is not available. I would appreciate any guidance or suggestions on how to resolve this issue. Specifically:

1. Is there an alternative version of JAX compatible with CUDA 11 and cuDNN 82 that you would recommend for VLN experiments?
2. Are there any additional steps or configurations required to successfully install JAX for this setup?

Any assistance or pointers in the right direction would be greatly appreciated as it is crucial for the progress of our project.

Thank you for your time and support.

Best regards

**Comment by jlin816** [comment]
JAX 0.3.* should also work fine with our codebase without that specific version. You could try:
```
pip3 install jax[cuda11_cudnn82] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
